language: ruby
dependencies:
  cache_directories:
  - public/assets
  - tmp/cache/assets
deploy:
  provider: heroku
  api_key:
    secure: N82OyI5dr8Li2JRg1l/WJXDjEKyLCxerQx1YGZcR16Ui97sCiG57liGpUKb7S6bUpQJrB0XBSiC197Q+0JgIt6u6gETcPjlvCoHmM04gvxZis8bZtxarT72xHZvE2M8jH++JSkggIc9kcU01YYuKZTK74rWVajCoYzvauJLjVHu9GyYxuST/j/mbQTcHpXCQIXADlKYuzvtOYexB74dmNU04Zc9Tlbgd11N8PPCmQEplW1j6h01px+8a8xSyt/zNQCN6uX+ELC6lxj7ZH4o9/GutcLrfY6hhM3xy9B/MuaUmY58hOLngx8Du/BZGC4+x4KHADoGFqnEWwO2Pvx8aTcI+hfQtrsAn6KpOMNEcVM7x1gbUShM5e3I+AFiXILKfCrsLdINPXmWQZTgL8j8EgSe2hd0TKZPoHAsbifwtyf0XUVFRjccjQNDKuXtovPoYBabZ0R+nJnbXxPfCNJMfwCFDc7dDliWCN91dkWJSiHYth+1+zcHx5R4ItvOxjqJmtiYDvLMKkYLnKLtM9gtR5TuhO9hv6jDLHMNp25PWQP92anNdVITD3jh8EpGebiZb5qpmQMnK3U2ltS63Q7cApzAHzT1Y+vPnhPeeidk2TmgMGr9XS822mCmFmwzmaJteVx/JcsA/iw0lcqALvZaZW67hQV9c9YZjMp3a+iWKNmY=
  app:
    master: coderdojo-japan
  run:
  - bundle exec rails db:migrate
  - bundle exec rails db:seed
  - bundle exec rails dojos:update_db_by_yaml
  - bundle exec rails dojo_event_services:upsert
  - bundle exec rails soundcloud_tracks:upsert
cache:
- bundler
before_install:
- gem install bundler
before_script:
- psql -c 'create database coderdojo_jp_test;' -U postgres
script:
- bundle exec rake db:migrate --trace
- bundle exec rake db:seed --trace
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec rspec spec; fi
- if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_PULL_REQUEST_SLUG" = "coderdojo-japan/coderdojo.jp"
  ]; then bundle exec rspec spec; fi
- if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_PULL_REQUEST_SLUG" != "coderdojo-japan/coderdojo.jp"
  ]; then bundle exec rspec spec --tag ~@scrivito; fi
env:
  global:
  - TZ='Asia/Tokyo'
  - secure: Ydqc7Pt/zR9aLs0WImHg6o+J7b5mcVZgcbrPuMg8p+Z75h74PZUh2OXJO7YCfrMp2AXpVygY2eK5ICACN3/ZnpO3pgR37zD97h3Dy68Du1c1vBD9owHb20kpGXqvZIoN81uG0rBKQqlSeNB4PWDWgduNtz6wdELlhP3Enl7FVgPZxTt623LNveISQXsG6OXjIx9ebgY/WAtO2x8YL3/06gwSwrQ8M31ZfSOPMH/VUrv9Eom1HQaJT2NlzEXLU+NTIOwH2CYRyHlXPGbW6x05IKDNBDR1i/3jcgr3q7Z+/XAgl1ho6UzVdMf+r31wfTamc88yy0eQQVMQjZFC+16iPZ4XV/adtJA534zQp8f7wmFEk3N6YTDvDCrlVQGaSW77tqG11XmDW5c/OLaisEl75+3QhI83A5VxTh9i3UHsO2JDBKbuT+GnU3UqM1m45NcMIO1SsG5SGLl5Wv9Y/2bHjW4TPjT+hSB36cyME/+Tmz4j2knS+Z4tlnldAVL+h1H/cc69CBqp0lXtiU5xGExewQ4PUhp/FHbeco5wJ1efMAgjgPeiyrDCIUzMWN4ivrKX806N5ddaUu6iOVa2pwpeLfvBMD7xj7iY/7EPsz2jsdNj0EK2w9IChBp5XuCRRr3ePNfbGw0fyEWmNryl6CQCxD8NxkgQYj0wCzQhW3pEx5s=
  - secure: O8lkYgonfTX9d+RYUXfLDVT6WgokzTeS/sE8CzzUjWuxsDiOldWAPLeEY5XVkEs9sI2T9g3Ia/dwJ9/X20r7Ny6A84qezMZgbF5pvLfxaU+K18A7I1OurII2PuEmPlol3Lyywi66EwhxYcl5GWJLfT1KIRsyj9J3xSy3ixyGJJ0YWUdEM4dUwJksVnzWriYSH2Wz9LEiJhneSXYTRsIFs0WlJ/ugmfRwspd8zNINfKo7sgtLR/QAtLLad71oQSkka4q/tN2ejcFnJvPFJq30LEHCUxcwRMVQwsDgIrkP/BEYK4w8artR/gK73slNd2FfHHMX8FDD9jjlfzoMP1RUrMB1SMl/V0sE6XAxugk0WFgvTxUM7NLFuWmUwoIfBtSHehfDziE+QzYH4KJUKIHw5Liz0QkobeSXiB8gd29u5Hy9PE3l3akmOOnB2fwzM3cJfZ0h3j+cbHiBISoZh5DF8T+SjsZ59g0azC9Deh9/bukef7jDSFpetudo3o0z2Vu7yQfctT+RT7+YQ+rCgndBDNAwFcoAW8YQBf8yN8CUGNJWByjV779m8+OKkVFH+Sa8syDMxIA+jPTWFiVNO8/9h0L2bMaFO9XMZgBNaKgrYn5h6KyKeRhs4+WJp9hX2GIHVA9XYC1lO+tIOvdtxAeJkZP+bAgbiT7r1qLpKKtQms8=
addons:
  postgresql: '9.4'
branches:
  only:
  - master
